Service:
  RegionId: cn-hangzhou
  DeployType: ros
  TenantType: SingleTenant
  DeployMetadata:
    ServiceInstanceNameRule:
      Prefix: sp-
    SupplierDeployMetadata:
      UserType: Aliyun
      RoleName: ${RoleName}
      SupplierTemplateConfigs:
        - Name: 单机版
          Url: 'ros_templates/template.yaml'
          PredefinedParameters:
            - Name: 低配版
              Parameters:
                EcsInstanceType: ['ecs.c6.large']
              Type: Noraml
              OrderList:
                - EcsInstanceType
            - Name: 基础版
              Parameters:
                EcsInstanceType: ['ecs.c6.xlarge']
              Type: Noraml
              OrderList:
                - EcsInstanceType
            - Name: 高配版
              Parameters:
                EcsInstanceType: ['ecs.c6.2xlarge']
              Type: Noraml
              OrderList:
                - EcsInstanceType
          HiddenParameterKeys:
            - EcsIntanceType
            - VpcId
            - VSwitchId
            - ZoneId
          ParameterMappings:
            - ParameterKey: RegionId
              ParameterMappingKeys:
                - VpcId
                - ZoneId
                - VSwitchId
              ParameterValueMapping:
                cn-hangzhou:
                  Parameters:
                    VpcId: ${VpcId}
                    ZoneId: ${ZoneId}
                    VSwitchId: ${VSwitchId}
      FileArtifactRelation:
        '{{ computenest::file::springboot }}':
          ArtifactId: ${Artifact.Artifact_1.ArtifactId}
          ArtifactVersion: ${Artifact.Artifact_1.ArtifactVersion}
    NetworkMetadata:
      EnablePrivateVpcConnection: false
  ServiceType: managed
  ServiceInfo:
    Locale: zh-CN
    ShortDescription: springboot demo
    Image: 'resources/icons/service_logo.png'
    Name: SpringBoot单机托管版
  ShareType: Public
  ApprovalType: Manual
Artifact:
  Artifact_1:
    ArtifactType: File
    ArtifactName: SpringBootPackage
    Description: 这是一个使用SpringBoot的测试包
    ArtifactProperty:
      RegionId: cn-hangzhou
      Url: 'resources/artifact_resources/file/package.tgz'